In [28]:
import pandas as pd 
data=pd.read_csv('flight_delay_predict.csv')
data.head()

,is_delay,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,Cancelled,Diverted,Distance,DistanceGroup,ArrDelay,ArrDelayMinutes,AirTime
0,1.0,2014,1,1,1,3,2014-01-01,UA,LAX,CA,ORD,IL,900,0.0,0.0,1744.0,7,43.0,43.0,218.0
1,0.0,2014,1,1,1,3,2014-01-01,AA,IAH,TX,DFW,TX,1750,0.0,0.0,224.0,1,2.0,2.0,50.0
2,1.0,2014,1,1,1,3,2014-01-01,AA,LAX,CA,ORD,IL,1240,0.0,0.0,1744.0,7,26.0,26.0,220.0
3,1.0,2014,1,1,1,3,2014-01-01,AA,DFW,TX,LAX,CA,1905,0.0,0.0,1235.0,5,159.0,159.0,169.0
4,0.0,2014,1,1,1,3,2014-01-01,AA,DFW,TX,CLT,NC,1115,0.0,0.0,936.0,4,-13.0,0.0,108.0

In [29]:
!pip install pytz

Requirement already satisfied: pytz in /home/sree/anaconda3/lib/python3.13/site-packages (2025.2)

In [30]:
data['is_delay'].value_counts(normalize=True)

is_delay
0.0    0.790087
1.0    0.209913
Name: proportion, dtype: float64

In [31]:
data.describe()

,is_delay,Year,Quarter,Month,DayofMonth,DayOfWeek,CRSDepTime,Cancelled,Diverted,Distance,DistanceGroup,ArrDelay,ArrDelayMinutes,AirTime
count,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06,1635590.0,1635590.0,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06,1.635590e+06
mean,2.099132e-01,2.016092e+03,2.543749e+00,6.629968e+00,1.574424e+01,3.931601e+00,1.313994e+03,0.0,0.0,1.011397e+03,4.455105e+00,6.015945e+00,1.372090e+01,1.345141e+02
std,4.072466e-01,1.378468e+00,1.106344e+00,3.402336e+00,8.776648e+00,1.989254e+00,4.990190e+02,0.0,0.0,5.381231e+02,2.143537e+00,4.298094e+01,3.943786e+01,6.346417e+01
min,0.000000e+00,2.014000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.0,0.0,2.240000e+02,1.000000e+00,-8.700000e+01,0.000000e+00,2.400000e+01
25%,0.000000e+00,2.015000e+03,2.000000e+00,4.000000e+00,8.000000e+00,2.000000e+00,9.100000e+02,0.0,0.0,6.060000e+02,3.000000e+00,-1.400000e+01,0.000000e+00,8.900000e+01
50%,0.000000e+00,2.016000e+03,3.000000e+00,7.000000e+00,1.600000e+01,4.000000e+00,1.310000e+03,0.0,0.0,8.680000e+02,4.000000e+00,-4.000000e+00,0.000000e+00,1.190000e+02
75%,0.000000e+00,2.017000e+03,4.000000e+00,1.000000e+01,2.300000e+01,6.000000e+00,1.720000e+03,0.0,0.0,1.440000e+03,6.000000e+00,1.000000e+01,1.000000e+01,1.820000e+02
max,1.000000e+00,2.018000e+03,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,2.359000e+03,0.0,0.0,2.296000e+03,1.000000e+01,2.142000e+03,2.142000e+03,3.860000e+02

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1635590 entries, 0 to 1635589
Data columns (total 20 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   is_delay           1635590 non-null  float64
 1   Year               1635590 non-null  int64
 2   Quarter            1635590 non-null  int64
 3   Month              1635590 non-null  int64
 4   DayofMonth         1635590 non-null  int64
 5   DayOfWeek          1635590 non-null  int64
 6   FlightDate         1635590 non-null  object
 7   Reporting_Airline  1635590 non-null  object
 8   Origin             1635590 non-null  object
 9   OriginState        1635590 non-null  object
 10  Dest               1635590 non-null  object
 11  DestState          1635590 non-null  object
 12  CRSDepTime         1635590 non-null  int64
 13  Cancelled          1635590 non-null  float64
 14  Diverted           1635590 non-null  float64
 15  Distance           1635590 non-null  float64
 16  DistanceGroup      1635590 non-null  int64
 17  ArrDelay           1635590 non-null  float64
 18  ArrDelayMinutes    1635590 non-null  float64
 19  AirTime            1635590 non-null  float64
dtypes: float64(7), int64(7), object(6)
memory usage: 249.6+ MB

In [33]:
data.shape

(1635590, 20)

In [34]:
data.isnull().sum()

is_delay             0
Year                 0
Quarter              0
Month                0
DayofMonth           0
DayOfWeek            0
FlightDate           0
Reporting_Airline    0
Origin               0
OriginState          0
Dest                 0
DestState            0
CRSDepTime           0
Cancelled            0
Diverted             0
Distance             0
DistanceGroup        0
ArrDelay             0
ArrDelayMinutes      0
AirTime              0
dtype: int64

In [35]:
df=data

In [36]:
df['FlightDate']

0          2014-01-01
1          2014-01-01
2          2014-01-01
3          2014-01-01
4          2014-01-01
              ...
1635585    2018-12-31
1635586    2018-12-31
1635587    2018-12-31
1635588    2018-12-31
1635589    2018-12-31
Name: FlightDate, Length: 1635590, dtype: object

In [37]:
df.drop(columns=['FlightDate'], inplace=True)
df.drop(columns=['OriginState'], inplace=True)
df.drop(columns=['DestState'], inplace=True)

In [38]:
df

,is_delay,Year,Quarter,Month,DayofMonth,DayOfWeek,Reporting_Airline,Origin,Dest,CRSDepTime,Cancelled,Diverted,Distance,DistanceGroup,ArrDelay,ArrDelayMinutes,AirTime
0,1.0,2014,1,1,1,3,UA,LAX,ORD,900,0.0,0.0,1744.0,7,43.0,43.0,218.0
1,0.0,2014,1,1,1,3,AA,IAH,DFW,1750,0.0,0.0,224.0,1,2.0,2.0,50.0
2,1.0,2014,1,1,1,3,AA,LAX,ORD,1240,0.0,0.0,1744.0,7,26.0,26.0,220.0
3,1.0,2014,1,1,1,3,AA,DFW,LAX,1905,0.0,0.0,1235.0,5,159.0,159.0,169.0
4,0.0,2014,1,1,1,3,AA,DFW,CLT,1115,0.0,0.0,936.0,4,-13.0,0.0,108.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1635585,1.0,2018,4,12,31,1,AA,DFW,DEN,1440,0.0,0.0,641.0,3,24.0,24.0,100.0
1635586,0.0,2018,4,12,31,1,DL,PHX,ATL,1420,0.0,0.0,1587.0,7,-14.0,0.0,179.0
1635587,1.0,2018,4,12,31,1,AA,ORD,SFO,1700,0.0,0.0,1846.0,8,39.0,39.0,272.0
1635588,0.0,2018,4,12,31,1,AA,ORD,LAX,720,0.0,0.0,1744.0,7,-10.0,0.0,240.0
1635589,1.0,2018,4,12,31,1,AA,DFW,DEN,1245,0.0,0.0,641.0,3,19.0,19.0,93.0

In [39]:
df['Reporting_Airline'].value_counts()

Reporting_Airline
AA    593362
UA    492842
DL    270148
WN    181439
OO     97799
Name: count, dtype: int64

In [40]:
df['Origin'].value_counts()

Origin
LAX    243778
ORD    213952
DFW    202683
SFO    201765
ATL    189967
DEN    186918
PHX    162353
IAH    132177
CLT    101997
Name: count, dtype: int64

In [41]:
df['Dest'].value_counts()

Dest
LAX    244848
ORD    216022
SFO    201693
DFW    201431
ATL    190907
DEN    184615
PHX    162280
IAH    131646
CLT    102148
Name: count, dtype: int64

In [42]:
# Create mappings with ranks starting from 0
airline_freq = {k: i for i, (k, _) in enumerate(df['Reporting_Airline'].value_counts().items())}
origin_freq = {k: i for i, (k, _) in enumerate(df['Origin'].value_counts().items())}
dest_freq = {k: i for i, (k, _) in enumerate(df['Dest'].value_counts().items())}

# Apply the mappings
df['Reporting_Airline'] = df['Reporting_Airline'].map(airline_freq)
df['Origin'] = df['Origin'].map(origin_freq) 
df['Dest'] = df['Dest'].map(dest_freq)

In [43]:
print(df[['Reporting_Airline', 'Origin', 'Dest']].head())

   Reporting_Airline  Origin  Dest
0                  1       0     1
1                  0       7     3
2                  0       0     1
3                  0       2     0
4                  0       2     8

In [44]:
print("Reporting_Airline Mapping:")
print(airline_freq)

print("\nOrigin Mapping:")
print(origin_freq)

print("\nDest Mapping:")
print(dest_freq)

Reporting_Airline Mapping:
{'AA': 0, 'UA': 1, 'DL': 2, 'WN': 3, 'OO': 4}

Origin Mapping:
{'LAX': 0, 'ORD': 1, 'DFW': 2, 'SFO': 3, 'ATL': 4, 'DEN': 5, 'PHX': 6, 'IAH': 7, 'CLT': 8}

Dest Mapping:
{'LAX': 0, 'ORD': 1, 'SFO': 2, 'DFW': 3, 'ATL': 4, 'DEN': 5, 'PHX': 6, 'IAH': 7, 'CLT': 8}

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1635590 entries, 0 to 1635589
Data columns (total 17 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   is_delay           1635590 non-null  float64
 1   Year               1635590 non-null  int64
 2   Quarter            1635590 non-null  int64
 3   Month              1635590 non-null  int64
 4   DayofMonth         1635590 non-null  int64
 5   DayOfWeek          1635590 non-null  int64
 6   Reporting_Airline  1635590 non-null  int64
 7   Origin             1635590 non-null  int64
 8   Dest               1635590 non-null  int64
 9   CRSDepTime         1635590 non-null  int64
 10  Cancelled          1635590 non-null  float64
 11  Diverted           1635590 non-null  float64
 12  Distance           1635590 non-null  float64
 13  DistanceGroup      1635590 non-null  int64
 14  ArrDelay           1635590 non-null  float64
 15  ArrDelayMinutes    1635590 non-null  float64
 16  AirTime            1635590 non-null  float64
dtypes: float64(7), int64(10)
memory usage: 212.1 MB

In [46]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /home/sree/anaconda3/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /home/sree/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

In [47]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop(columns=['is_delay'])  # Replace 'FlightDelay' with your actual target column
y = df['is_delay']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ANN

In [48]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /home/sree/anaconda3/lib/python3.13/site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.20.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/sree/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/sree/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/sree/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /home/sree/anaconda3/lib/python3.13/site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /home/sree/anaconda3/lib/python3.13/site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /home/sree/anaconda3/lib/python3.13/site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/sree/anaconda3/lib/python3.13/site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /home/sree/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Use sigmoid for binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=5, batch_size=32,
                    validation_split=0.2, verbose=1)

# Evaluate the model on test set
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Accuracy: {test_accuracy:.4f}")

/home/sree/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-09-06 11:50:45.986667: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 66993728 exceeds 10% of free system memory.

Epoch 1/5
28624/32712 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - accuracy: 0.9924 - loss: 0.0196

## XGB

In [ ]:
!pip install xgboost

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Initialize XGBoost classifier
xgb_model = xgb.XGBClassifier(
    objective='binary:logistic',  # Binary classification
    eval_metric='logloss',  # Log loss for binary classification
    use_label_encoder=False,
    learning_rate=0.1,
    max_depth=6,
    n_estimators=100,
    random_state=42
)

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred = xgb_model.predict(X_test)

In [ ]:
# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)  
print(f"XGBoost Accuracy: {accuracy:.4f}")

In [ ]:
import joblib 
joblib.dump(xgb_model, "xgb_model.pkl")
print("Model saved successfully!")

In [ ]:
import gradio as gr
import xgboost as xgb
import pandas as pd
#import joblib  # To save/load the model

# # Load the trained model
# model = joblib.load("grnn_model.pkl")  # Ensure this file exists

# # Mappings
# reporting_airline_mapping = {'AA': 0, 'UA': 1, 'DL': 2, 'WN': 3, 'OO': 4}
# origin_mapping = {'LAX': 0, 'ORD': 1, 'DFW': 2, 'SFO': 3, 'ATL': 4, 'DEN': 5, 'PHX': 6, 'IAH': 7, 'CLT': 8}
# dest_mapping = {'LAX': 0, 'ORD': 1, 'SFO': 2, 'DFW': 3, 'ATL': 4, 'DEN': 5, 'PHX': 6, 'IAH': 7, 'CLT': 8}

# # Define feature columns
# feature_columns = [
#     "Year", "Quarter", "Month", "DayofMonth", "DayOfWeek",
#     "Reporting_Airline", "Origin", "Dest", "CRSDepTime",
#     "Cancelled", "Diverted", "Distance", "DistanceGroup",
#     "ArrDelay", "ArrDelayMinutes", "AirTime"
# ]

# # Prediction function with automatic mapping
# def predict_delay(Year, Quarter, Month, DayofMonth, DayOfWeek,
#                   Reporting_Airline, Origin, Dest, CRSDepTime,
#                   Cancelled, Diverted, Distance, DistanceGroup,
#                   ArrDelay, ArrDelayMinutes, AirTime):

#     # Convert categorical inputs to numerical values
#     Reporting_Airline = reporting_airline_mapping.get(Reporting_Airline, -1)
#     Origin = origin_mapping.get(Origin, -1)
#     Dest = dest_mapping.get(Dest, -1)

#     # Handle unknown inputs (if -1, return an error message)
#     if -1 in [Reporting_Airline, Origin, Dest]:
#         return "Error: Invalid Airline, Origin, or Destination entered!"

#     # Create DataFrame from input
#     input_data = pd.DataFrame([[Year, Quarter, Month, DayofMonth, DayOfWeek,
#                                 Reporting_Airline, Origin, Dest, CRSDepTime,
#                                 Cancelled, Diverted, Distance, DistanceGroup,
#                                 ArrDelay, ArrDelayMinutes, AirTime]], 
#                               columns=feature_columns)
    
#     # Predict using the trained model
#     prediction = model.predict(input_data)[0]
    
#     # Return readable result
#     return "Delayed" if prediction == 1 else "On-Time"

# # Create Gradio Interface
# gr_interface = gr.Interface(
#     fn=predict_delay,
#     inputs=[
#         gr.Number(label="Year", value=2024),
#         gr.Number(label="Quarter", value=1),
#         gr.Number(label="Month", value=1),
#         gr.Number(label="DayofMonth", value=1),
#         gr.Number(label="DayOfWeek", value=3),
#         gr.Dropdown(choices=list(reporting_airline_mapping.keys()), label="Reporting Airline"),
#         gr.Dropdown(choices=list(origin_mapping.keys()), label="Origin"),
#         gr.Dropdown(choices=list(dest_mapping.keys()), label="Destination"),
#         gr.Number(label="CRSDepTime", value=1200),
#         gr.Number(label="Cancelled", value=0),
#         gr.Number(label="Diverted", value=0),
#         gr.Number(label="Distance", value=500),
#         gr.Number(label="DistanceGroup", value=3),
#         gr.Number(label="ArrDelay", value=0),
#         gr.Number(label="ArrDelayMinutes", value=0),
#         gr.Number(label="AirTime", value=120)
#     ],
#     outputs="text",
#     title="Flight Delay Prediction",
#     description="Enter flight details to predict if the flight will be delayed."


Launch the app
gr_interface.launch()